"""
Report Generator — Phase 3
Generates human-readable Markdown reports from analysis results.
"""
from __future__ import annotations

from analysis.runner import ExperimentResult
from analysis.stats import ComparisonReport, DifficultyAnalyzer


def generate_markdown_report(comparison: ComparisonReport, experiment: ExperimentResult) -> str:
    """Generate a full Markdown difficulty analysis report."""
    analyzer = DifficultyAnalyzer()
    ranked = analyzer.rank_by_difficulty(experiment)

    lines = [
        "# Wordle Difficulty Analysis Report",
        "",
        f"**Strategy**: `{comparison.strategy_name}`",
        f"**Puzzles analyzed**: {len(comparison.words)}",
        "",
        "## Summary Statistics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| LLM avg guesses | {comparison.avg_llm_guesses:.2f} |",
        f"| Human avg guesses | {comparison.avg_human_guesses:.2f} |",
        f"| Pearson r | **{comparison.correlation.r:.3f}** |",
        f"| p-value | {comparison.correlation.p_value:.4f} |",
        f"| Sample size | {comparison.correlation.n} |",
        f"| Statistically significant | {'✅ Yes' if comparison.correlation.significant else '❌ No'} |",
        "",
        "## Interpretation",
        "",
    ]

    r = comparison.correlation.r
    sig = comparison.correlation.significant
    n = comparison.correlation.n

    if not sig and n < 8:
        caveat = f" *(note: n={n} is too small for statistical significance — use ≥10 words)*"
    elif not sig:
        caveat = " *(not statistically significant — p > 0.05)*"
    else:
        caveat = ""

    if r >= 0.6:
        strength = "**Strong correlation**"
        detail = "LLM difficulty scores closely mirror human difficulty perception."
    elif r >= 0.4:
        strength = "**Moderate correlation**"
        detail = "LLM scores show meaningful alignment with human difficulty."
    elif r >= 0.2:
        strength = "**Weak correlation**"
        detail = "LLM scores have limited alignment with human difficulty."
    else:
        strength = "**Very weak / no correlation**"
        detail = "LLM scores do not reflect human difficulty perception."

    lines.append(f"{strength}: {detail}{caveat}")
    lines.append("")
    lines.append("## Puzzle Difficulty Ranking (Hardest → Easiest)")
    lines.append("")
    lines.append("| Rank | Word | LLM Avg Guesses | Human Avg Guesses |")
    lines.append("|------|------|-----------------|-------------------|")

    human_map = dict(zip(comparison.words, comparison.human_scores))
    for rank, (word, score) in enumerate(ranked, 1):
        human = human_map.get(word, "N/A")
        human_str = f"{human:.2f}" if isinstance(human, float) else str(human)
        lines.append(f"| {rank} | {word} | {score:.2f} | {human_str} |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by LLM Game Difficulty Framework (paper: arXiv:2410.02829)*")

    return "\n".join(lines)
